# Project identification
sonar.projectKey=P09-InterviewPrepApp
sonar.projectName=Interview Prep App - Backend
sonar.projectVersion=0.0.0

# Source and test files
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,paraphrase.js,refine_qas.js,seed.js,server.js,app.js,jest.config.js

# Disable coverage requirements
sonar.coverage.exclusions=**/*

# Language
sonar.language=js
