apiVersion: v1
kind: Service
metadata:
  name: interview-prep-service
  namespace: interview-prep
spec:
  type: NodePort
  selector:
    app: interview-prep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
